on: [push, pull_request]
name: Test
permissions:
  contents: read

jobs:
  test:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20', '1.19', '1.18']
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test ./...
