on: [push, pull_request]
name: Test
permissions:
  contents: read

jobs:
  test:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20', '1.19', '1.18']
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test ./...
